# Generated by Django 4.2.17 on 2025-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_car_saloon'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
