# Generated by Django 4.2.17 on 2025-01-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reservation_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
